/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BurgerButton: typeof import('./src/components/ui/BurgerButton.vue')['default']
    CodeButton: typeof import('./src/components/ui/CodeButton.vue')['default']
    Heist: typeof import('./src/components/Heist.vue')['default']
    MenuFullscreen: typeof import('./src/components/ui/MenuFullscreen.vue')['default']
    Spinner: typeof import('./src/components/ui/Spinner.vue')['default']
    SVGCircle: typeof import('./src/components/ui/SVGCircle.vue')['default']
    Venus: typeof import('./src/components/Venus.vue')['default']
  }
}
