/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BurgerButton: typeof import('./src/components/ui/BurgerButton.vue')['default']
    MenuFullscreen: typeof import('./src/components/ui/MenuFullscreen.vue')['default']
    Spinner: typeof import('./src/components/ui/Spinner.vue')['default']
    SVGCircle: typeof import('./src/components/ui/SVGCircle.vue')['default']
    Venus: typeof import('./src/components/Venus.vue')['default']
  }
}
